# Generated by GitHub Copilot using Claude Sonnet 4.5
# Description: Production-ready Dockerfile for MCP Server for VS Code with N|Solid runtime

# N|Solid runtime base image (Node.js 24.x Krypton LTS)
FROM nodesource/nsolid:krypton-latest

# Create non-root user for security
RUN groupadd -r nodejs && useradd -r -g nodejs nodejs

WORKDIR /app

# Copy dependency manifests
COPY package*.json ./

# Install dependencies
RUN npm ci --production && npm cache clean --force

# Copy compiled output
COPY out/ ./out/

# Set ownership to non-root user
RUN chown -R nodejs:nodejs /app

# Switch to non-root user
USER nodejs

# N|Solid configuration via environment variables
ENV NSOLID_APPNAME=mcp-server-vscode
ENV NSOLID_TAGS=docker,production
ENV NSOLID_TRACING_ENABLED=1
ENV NSOLID_OTLP=otlp
ENV NSOLID_OTLP_CONFIG={"url":"http://otel-collector:4318/v1/traces","protocol":"http"}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD nsolid -e "require('http').get('http://localhost:8991/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"

# Expose the default MCP server port
EXPOSE 8991

# Start with N|Solid runtime
CMD ["nsolid", "./out/mcp/standalone-server.js"]
