#!/bin/bash
# Generated by GitHub Copilot using Claude Sonnet 4.5
# Description: Quick start script for running MCP Server with N|Solid runtime

set -e

echo "Starting MCP Server for VS Code with N|Solid runtime..."

# Check if nsolid is installed
if ! command -v nsolid &> /dev/null; then
    echo "Error: N|Solid runtime not found."
    echo ""
    echo "Install N|Solid:"
    echo "  macOS: brew install nsolid"
    echo "  Linux: curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash - && sudo apt-get install nsolid -y"
    echo "  Docker: docker pull nodesource/nsolid:krypton-latest"
    exit 1
fi

# Display N|Solid version
echo "N|Solid version: $(nsolid -vv)"
echo "Node.js version: $(nsolid -v)"
echo ""

# Set default environment variables
export NSOLID_APPNAME="${NSOLID_APPNAME:-mcp-server-vscode}"
export NSOLID_TRACING_ENABLED="${NSOLID_TRACING_ENABLED:-1}"
export VSCODE_BRIDGE_PORT="${VSCODE_BRIDGE_PORT:-8991}"

# Optional: Set OTLP endpoint if monitoring stack is running
if [ -z "$NSOLID_OTLP" ]; then
    # Check if OTLP collector is available
    if curl -s http://localhost:4318/v1/traces > /dev/null 2>&1; then
        export NSOLID_OTLP=otlp
        export NSOLID_OTLP_CONFIG='{"url":"http://localhost:4318/v1/traces","protocol":"http"}'
        echo "OTLP collector detected, enabling telemetry export..."
    fi
fi

echo "Configuration:"
echo "  App Name: $NSOLID_APPNAME"
echo "  Bridge Port: $VSCODE_BRIDGE_PORT"
echo "  Tracing: $NSOLID_TRACING_ENABLED"
if [ -n "$NSOLID_OTLP" ]; then
    echo "  OTLP: $NSOLID_OTLP"
fi
echo ""

# Run the server
echo "Starting server..."
nsolid ./out/mcp/standalone-server.js
