#!/bin/bash
# Generated by GitHub Copilot using Claude Sonnet 4.5
# This script updates npm dependencies to fix security vulnerabilities
# Updates @modelcontextprotocol/sdk and its transitive dependencies



echo "Updating dependencies to fix security vulnerabilities..."
echo "This will update:"
echo "  - @modelcontextprotocol/sdk: 1.13.2 -> 1.15.0+"
echo "  - ajv (transitive dependency)"
echo "  - body-parser (transitive dependency)"
echo "  - qs (transitive dependency)"
echo ""

# Remove package-lock.json to force a fresh install
rm -f package-lock.json

# Install dependencies
npm install

# Run audit to verify fixes
echo ""
echo "Running security audit..."
npm audit

echo ""
echo "Update complete! Please review the audit results above."
